using System;
using System.IO;

namespace MessagePipe.Common
{
    internal static class TypeContracts
    {
        public static Type GetPacketType(int id)
        {
            // method body will be generated by code generator
            switch (id)
            {
                case 0:
                    return typeof(Packet);
                default:
                    throw new ArgumentOutOfRangeException(nameof(id), id, null);
            }
        }

        public static Packet CreateObject(Type type, MemoryStream stream)
        {
            // method body will be generated by code generator
            return null;
        }
    }
}